// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UcStudent.proto

package com.protobuf.protobuftest.protobuf;

public final class Student {
  private Student() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UcStudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protobuf.protobuftest.UcStudent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * string 类型  
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    String getUserId();
    /**
     * <pre>
     * string 类型  
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string name = 2;</code>
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
     */
    int getSexValue();
    /**
     * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
     */
    UcStudent.Sex getSex();

    /**
     * <code>string mobile = 4;</code>
     */
    String getMobile();
    /**
     * <code>string mobile = 4;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <code>string email = 5;</code>
     */
    String getEmail();
    /**
     * <code>string email = 5;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string photo = 6;</code>
     */
    String getPhoto();
    /**
     * <code>string photo = 6;</code>
     */
    com.google.protobuf.ByteString
        getPhotoBytes();

    /**
     * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
     */
    int getCardTypeValue();
    /**
     * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
     */
    UcStudent.CardType getCardType();

    /**
     * <code>string cardId = 8;</code>
     */
    String getCardId();
    /**
     * <code>string cardId = 8;</code>
     */
    com.google.protobuf.ByteString
        getCardIdBytes();

    /**
     * <code>string englishName = 9;</code>
     */
    String getEnglishName();
    /**
     * <code>string englishName = 9;</code>
     */
    com.google.protobuf.ByteString
        getEnglishNameBytes();

    /**
     * <code>string nationality = 10;</code>
     */
    String getNationality();
    /**
     * <code>string nationality = 10;</code>
     */
    com.google.protobuf.ByteString
        getNationalityBytes();

    /**
     * <code>string nationalityName = 11;</code>
     */
    String getNationalityName();
    /**
     * <code>string nationalityName = 11;</code>
     */
    com.google.protobuf.ByteString
        getNationalityNameBytes();

    /**
     * <code>string nation = 12;</code>
     */
    String getNation();
    /**
     * <code>string nation = 12;</code>
     */
    com.google.protobuf.ByteString
        getNationBytes();

    /**
     * <code>string nationName = 13;</code>
     */
    String getNationName();
    /**
     * <code>string nationName = 13;</code>
     */
    com.google.protobuf.ByteString
        getNationNameBytes();

    /**
     * <code>string province = 14;</code>
     */
    String getProvince();
    /**
     * <code>string province = 14;</code>
     */
    com.google.protobuf.ByteString
        getProvinceBytes();

    /**
     * <code>string provinceName = 15;</code>
     */
    String getProvinceName();
    /**
     * <code>string provinceName = 15;</code>
     */
    com.google.protobuf.ByteString
        getProvinceNameBytes();

    /**
     * <code>string city = 16;</code>
     */
    String getCity();
    /**
     * <code>string city = 16;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string cityName = 17;</code>
     */
    String getCityName();
    /**
     * <code>string cityName = 17;</code>
     */
    com.google.protobuf.ByteString
        getCityNameBytes();

    /**
     * <code>string address = 18;</code>
     */
    String getAddress();
    /**
     * <code>string address = 18;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string postcode = 19;</code>
     */
    String getPostcode();
    /**
     * <code>string postcode = 19;</code>
     */
    com.google.protobuf.ByteString
        getPostcodeBytes();

    /**
     * <code>string birthday = 20;</code>
     */
    String getBirthday();
    /**
     * <code>string birthday = 20;</code>
     */
    com.google.protobuf.ByteString
        getBirthdayBytes();
  }
  /**
   * Protobuf type {@code com.protobuf.protobuftest.UcStudent}
   */
  public  static final class UcStudent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protobuf.protobuftest.UcStudent)
      UcStudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UcStudent.newBuilder() to construct.
    private UcStudent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UcStudent() {
      userId_ = "";
      name_ = "";
      sex_ = 0;
      mobile_ = "";
      email_ = "";
      photo_ = "";
      cardType_ = 0;
      cardId_ = "";
      englishName_ = "";
      nationality_ = "";
      nationalityName_ = "";
      nation_ = "";
      nationName_ = "";
      province_ = "";
      provinceName_ = "";
      city_ = "";
      cityName_ = "";
      address_ = "";
      postcode_ = "";
      birthday_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UcStudent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              sex_ = rawValue;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              photo_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              cardType_ = rawValue;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              cardId_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              englishName_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              nationality_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              nationalityName_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              nation_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              nationName_ = s;
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              province_ = s;
              break;
            }
            case 122: {
              String s = input.readStringRequireUtf8();

              provinceName_ = s;
              break;
            }
            case 130: {
              String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 138: {
              String s = input.readStringRequireUtf8();

              cityName_ = s;
              break;
            }
            case 146: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 154: {
              String s = input.readStringRequireUtf8();

              postcode_ = s;
              break;
            }
            case 162: {
              String s = input.readStringRequireUtf8();

              birthday_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Student.internal_static_com_protobuf_protobuftest_UcStudent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Student.internal_static_com_protobuf_protobuftest_UcStudent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UcStudent.class, Builder.class);
    }

    /**
     * <pre>
     *性别枚举
     * </pre>
     *
     * Protobuf enum {@code com.protobuf.protobuftest.UcStudent.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Female = 0;</code>
       */
      Female(0),
      /**
       * <code>MALE = 1;</code>
       */
      MALE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Female = 0;</code>
       */
      public static final int Female_VALUE = 0;
      /**
       * <code>MALE = 1;</code>
       */
      public static final int MALE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Sex valueOf(int value) {
        return forNumber(value);
      }

      public static Sex forNumber(int value) {
        switch (value) {
          case 0: return Female;
          case 1: return MALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sex> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return UcStudent.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sex(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.protobuf.protobuftest.UcStudent.Sex)
    }

    /**
     * Protobuf enum {@code com.protobuf.protobuftest.UcStudent.CardType}
     */
    public enum CardType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 0;</code>
       */
      DEFAULT(0),
      /**
       * <pre>
       *大陆
       * </pre>
       *
       * <code>MAINLAND = 1;</code>
       */
      MAINLAND(1),
      /**
       * <pre>
       *护照
       * </pre>
       *
       * <code>PASSPORT = 2;</code>
       */
      PASSPORT(2),
      /**
       * <pre>
       *军官
       * </pre>
       *
       * <code>OFFICER = 3;</code>
       */
      OFFICER(3),
      /**
       * <pre>
       *境外
       * </pre>
       *
       * <code>ABROAD = 10;</code>
       */
      ABROAD(10),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DEFAULT = 0;</code>
       */
      public static final int DEFAULT_VALUE = 0;
      /**
       * <pre>
       *大陆
       * </pre>
       *
       * <code>MAINLAND = 1;</code>
       */
      public static final int MAINLAND_VALUE = 1;
      /**
       * <pre>
       *护照
       * </pre>
       *
       * <code>PASSPORT = 2;</code>
       */
      public static final int PASSPORT_VALUE = 2;
      /**
       * <pre>
       *军官
       * </pre>
       *
       * <code>OFFICER = 3;</code>
       */
      public static final int OFFICER_VALUE = 3;
      /**
       * <pre>
       *境外
       * </pre>
       *
       * <code>ABROAD = 10;</code>
       */
      public static final int ABROAD_VALUE = 10;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static CardType valueOf(int value) {
        return forNumber(value);
      }

      public static CardType forNumber(int value) {
        switch (value) {
          case 0: return DEFAULT;
          case 1: return MAINLAND;
          case 2: return PASSPORT;
          case 3: return OFFICER;
          case 10: return ABROAD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CardType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CardType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CardType>() {
              public CardType findValueByNumber(int number) {
                return CardType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return UcStudent.getDescriptor().getEnumTypes().get(1);
      }

      private static final CardType[] VALUES = values();

      public static CardType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CardType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.protobuf.protobuftest.UcStudent.CardType)
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile Object userId_;
    /**
     * <pre>
     * string 类型  
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * string 类型  
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
     */
    public Sex getSex() {
      @SuppressWarnings("deprecation")
      Sex result = Sex.valueOf(sex_);
      return result == null ? Sex.UNRECOGNIZED : result;
    }

    public static final int MOBILE_FIELD_NUMBER = 4;
    private volatile Object mobile_;
    /**
     * <code>string mobile = 4;</code>
     */
    public String getMobile() {
      Object ref = mobile_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>string mobile = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      Object ref = mobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 5;
    private volatile Object email_;
    /**
     * <code>string email = 5;</code>
     */
    public String getEmail() {
      Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHOTO_FIELD_NUMBER = 6;
    private volatile Object photo_;
    /**
     * <code>string photo = 6;</code>
     */
    public String getPhoto() {
      Object ref = photo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        photo_ = s;
        return s;
      }
    }
    /**
     * <code>string photo = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPhotoBytes() {
      Object ref = photo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        photo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARDTYPE_FIELD_NUMBER = 7;
    private int cardType_;
    /**
     * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
     */
    public int getCardTypeValue() {
      return cardType_;
    }
    /**
     * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
     */
    public CardType getCardType() {
      @SuppressWarnings("deprecation")
      CardType result = CardType.valueOf(cardType_);
      return result == null ? CardType.UNRECOGNIZED : result;
    }

    public static final int CARDID_FIELD_NUMBER = 8;
    private volatile Object cardId_;
    /**
     * <code>string cardId = 8;</code>
     */
    public String getCardId() {
      Object ref = cardId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cardId_ = s;
        return s;
      }
    }
    /**
     * <code>string cardId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCardIdBytes() {
      Object ref = cardId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cardId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENGLISHNAME_FIELD_NUMBER = 9;
    private volatile Object englishName_;
    /**
     * <code>string englishName = 9;</code>
     */
    public String getEnglishName() {
      Object ref = englishName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        englishName_ = s;
        return s;
      }
    }
    /**
     * <code>string englishName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getEnglishNameBytes() {
      Object ref = englishName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        englishName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATIONALITY_FIELD_NUMBER = 10;
    private volatile Object nationality_;
    /**
     * <code>string nationality = 10;</code>
     */
    public String getNationality() {
      Object ref = nationality_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nationality_ = s;
        return s;
      }
    }
    /**
     * <code>string nationality = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNationalityBytes() {
      Object ref = nationality_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nationality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATIONALITYNAME_FIELD_NUMBER = 11;
    private volatile Object nationalityName_;
    /**
     * <code>string nationalityName = 11;</code>
     */
    public String getNationalityName() {
      Object ref = nationalityName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nationalityName_ = s;
        return s;
      }
    }
    /**
     * <code>string nationalityName = 11;</code>
     */
    public com.google.protobuf.ByteString
        getNationalityNameBytes() {
      Object ref = nationalityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nationalityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATION_FIELD_NUMBER = 12;
    private volatile Object nation_;
    /**
     * <code>string nation = 12;</code>
     */
    public String getNation() {
      Object ref = nation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nation_ = s;
        return s;
      }
    }
    /**
     * <code>string nation = 12;</code>
     */
    public com.google.protobuf.ByteString
        getNationBytes() {
      Object ref = nation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATIONNAME_FIELD_NUMBER = 13;
    private volatile Object nationName_;
    /**
     * <code>string nationName = 13;</code>
     */
    public String getNationName() {
      Object ref = nationName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nationName_ = s;
        return s;
      }
    }
    /**
     * <code>string nationName = 13;</code>
     */
    public com.google.protobuf.ByteString
        getNationNameBytes() {
      Object ref = nationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVINCE_FIELD_NUMBER = 14;
    private volatile Object province_;
    /**
     * <code>string province = 14;</code>
     */
    public String getProvince() {
      Object ref = province_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        province_ = s;
        return s;
      }
    }
    /**
     * <code>string province = 14;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVINCENAME_FIELD_NUMBER = 15;
    private volatile Object provinceName_;
    /**
     * <code>string provinceName = 15;</code>
     */
    public String getProvinceName() {
      Object ref = provinceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        provinceName_ = s;
        return s;
      }
    }
    /**
     * <code>string provinceName = 15;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceNameBytes() {
      Object ref = provinceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        provinceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 16;
    private volatile Object city_;
    /**
     * <code>string city = 16;</code>
     */
    public String getCity() {
      Object ref = city_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 16;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITYNAME_FIELD_NUMBER = 17;
    private volatile Object cityName_;
    /**
     * <code>string cityName = 17;</code>
     */
    public String getCityName() {
      Object ref = cityName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cityName_ = s;
        return s;
      }
    }
    /**
     * <code>string cityName = 17;</code>
     */
    public com.google.protobuf.ByteString
        getCityNameBytes() {
      Object ref = cityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 18;
    private volatile Object address_;
    /**
     * <code>string address = 18;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 18;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSTCODE_FIELD_NUMBER = 19;
    private volatile Object postcode_;
    /**
     * <code>string postcode = 19;</code>
     */
    public String getPostcode() {
      Object ref = postcode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        postcode_ = s;
        return s;
      }
    }
    /**
     * <code>string postcode = 19;</code>
     */
    public com.google.protobuf.ByteString
        getPostcodeBytes() {
      Object ref = postcode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        postcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 20;
    private volatile Object birthday_;
    /**
     * <code>string birthday = 20;</code>
     */
    public String getBirthday() {
      Object ref = birthday_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        birthday_ = s;
        return s;
      }
    }
    /**
     * <code>string birthday = 20;</code>
     */
    public com.google.protobuf.ByteString
        getBirthdayBytes() {
      Object ref = birthday_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        birthday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (sex_ != Sex.Female.getNumber()) {
        output.writeEnum(3, sex_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mobile_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, email_);
      }
      if (!getPhotoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, photo_);
      }
      if (cardType_ != CardType.DEFAULT.getNumber()) {
        output.writeEnum(7, cardType_);
      }
      if (!getCardIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, cardId_);
      }
      if (!getEnglishNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, englishName_);
      }
      if (!getNationalityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, nationality_);
      }
      if (!getNationalityNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, nationalityName_);
      }
      if (!getNationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, nation_);
      }
      if (!getNationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, nationName_);
      }
      if (!getProvinceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, province_);
      }
      if (!getProvinceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, provinceName_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, city_);
      }
      if (!getCityNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, cityName_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, address_);
      }
      if (!getPostcodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 19, postcode_);
      }
      if (!getBirthdayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, birthday_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (sex_ != Sex.Female.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, sex_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mobile_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, email_);
      }
      if (!getPhotoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, photo_);
      }
      if (cardType_ != CardType.DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, cardType_);
      }
      if (!getCardIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, cardId_);
      }
      if (!getEnglishNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, englishName_);
      }
      if (!getNationalityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, nationality_);
      }
      if (!getNationalityNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, nationalityName_);
      }
      if (!getNationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, nation_);
      }
      if (!getNationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, nationName_);
      }
      if (!getProvinceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, province_);
      }
      if (!getProvinceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, provinceName_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, city_);
      }
      if (!getCityNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, cityName_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, address_);
      }
      if (!getPostcodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, postcode_);
      }
      if (!getBirthdayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, birthday_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UcStudent)) {
        return super.equals(obj);
      }
      UcStudent other = (UcStudent) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (sex_ != other.sex_) return false;
      if (!getMobile()
          .equals(other.getMobile())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getPhoto()
          .equals(other.getPhoto())) return false;
      if (cardType_ != other.cardType_) return false;
      if (!getCardId()
          .equals(other.getCardId())) return false;
      if (!getEnglishName()
          .equals(other.getEnglishName())) return false;
      if (!getNationality()
          .equals(other.getNationality())) return false;
      if (!getNationalityName()
          .equals(other.getNationalityName())) return false;
      if (!getNation()
          .equals(other.getNation())) return false;
      if (!getNationName()
          .equals(other.getNationName())) return false;
      if (!getProvince()
          .equals(other.getProvince())) return false;
      if (!getProvinceName()
          .equals(other.getProvinceName())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getCityName()
          .equals(other.getCityName())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getPostcode()
          .equals(other.getPostcode())) return false;
      if (!getBirthday()
          .equals(other.getBirthday())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getPhoto().hashCode();
      hash = (37 * hash) + CARDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + cardType_;
      hash = (37 * hash) + CARDID_FIELD_NUMBER;
      hash = (53 * hash) + getCardId().hashCode();
      hash = (37 * hash) + ENGLISHNAME_FIELD_NUMBER;
      hash = (53 * hash) + getEnglishName().hashCode();
      hash = (37 * hash) + NATIONALITY_FIELD_NUMBER;
      hash = (53 * hash) + getNationality().hashCode();
      hash = (37 * hash) + NATIONALITYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNationalityName().hashCode();
      hash = (37 * hash) + NATION_FIELD_NUMBER;
      hash = (53 * hash) + getNation().hashCode();
      hash = (37 * hash) + NATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNationName().hashCode();
      hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
      hash = (53 * hash) + getProvince().hashCode();
      hash = (37 * hash) + PROVINCENAME_FIELD_NUMBER;
      hash = (53 * hash) + getProvinceName().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + CITYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCityName().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + POSTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getPostcode().hashCode();
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + getBirthday().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UcStudent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UcStudent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UcStudent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UcStudent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UcStudent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UcStudent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UcStudent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UcStudent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UcStudent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UcStudent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UcStudent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UcStudent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UcStudent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protobuf.protobuftest.UcStudent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protobuf.protobuftest.UcStudent)
        UcStudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Student.internal_static_com_protobuf_protobuftest_UcStudent_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Student.internal_static_com_protobuf_protobuftest_UcStudent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UcStudent.class, Builder.class);
      }

      // Construct using com.protobuf.protobuftest.protobuf.Student.UcStudent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        name_ = "";

        sex_ = 0;

        mobile_ = "";

        email_ = "";

        photo_ = "";

        cardType_ = 0;

        cardId_ = "";

        englishName_ = "";

        nationality_ = "";

        nationalityName_ = "";

        nation_ = "";

        nationName_ = "";

        province_ = "";

        provinceName_ = "";

        city_ = "";

        cityName_ = "";

        address_ = "";

        postcode_ = "";

        birthday_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Student.internal_static_com_protobuf_protobuftest_UcStudent_descriptor;
      }

      @Override
      public UcStudent getDefaultInstanceForType() {
        return UcStudent.getDefaultInstance();
      }

      @Override
      public UcStudent build() {
        UcStudent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UcStudent buildPartial() {
        UcStudent result = new UcStudent(this);
        result.userId_ = userId_;
        result.name_ = name_;
        result.sex_ = sex_;
        result.mobile_ = mobile_;
        result.email_ = email_;
        result.photo_ = photo_;
        result.cardType_ = cardType_;
        result.cardId_ = cardId_;
        result.englishName_ = englishName_;
        result.nationality_ = nationality_;
        result.nationalityName_ = nationalityName_;
        result.nation_ = nation_;
        result.nationName_ = nationName_;
        result.province_ = province_;
        result.provinceName_ = provinceName_;
        result.city_ = city_;
        result.cityName_ = cityName_;
        result.address_ = address_;
        result.postcode_ = postcode_;
        result.birthday_ = birthday_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UcStudent) {
          return mergeFrom((UcStudent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UcStudent other) {
        if (other == UcStudent.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getPhoto().isEmpty()) {
          photo_ = other.photo_;
          onChanged();
        }
        if (other.cardType_ != 0) {
          setCardTypeValue(other.getCardTypeValue());
        }
        if (!other.getCardId().isEmpty()) {
          cardId_ = other.cardId_;
          onChanged();
        }
        if (!other.getEnglishName().isEmpty()) {
          englishName_ = other.englishName_;
          onChanged();
        }
        if (!other.getNationality().isEmpty()) {
          nationality_ = other.nationality_;
          onChanged();
        }
        if (!other.getNationalityName().isEmpty()) {
          nationalityName_ = other.nationalityName_;
          onChanged();
        }
        if (!other.getNation().isEmpty()) {
          nation_ = other.nation_;
          onChanged();
        }
        if (!other.getNationName().isEmpty()) {
          nationName_ = other.nationName_;
          onChanged();
        }
        if (!other.getProvince().isEmpty()) {
          province_ = other.province_;
          onChanged();
        }
        if (!other.getProvinceName().isEmpty()) {
          provinceName_ = other.provinceName_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getCityName().isEmpty()) {
          cityName_ = other.cityName_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getPostcode().isEmpty()) {
          postcode_ = other.postcode_;
          onChanged();
        }
        if (!other.getBirthday().isEmpty()) {
          birthday_ = other.birthday_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UcStudent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UcStudent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userId_ = "";
      /**
       * <pre>
       * string 类型  
       * </pre>
       *
       * <code>string userId = 1;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * string 类型  
       * </pre>
       *
       * <code>string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * string 类型  
       * </pre>
       *
       * <code>string userId = 1;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string 类型  
       * </pre>
       *
       * <code>string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string 类型  
       * </pre>
       *
       * <code>string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ = 0;
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
       */
      public int getSexValue() {
        return sex_;
      }
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
       */
      public Builder setSexValue(int value) {
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
       */
      public Sex getSex() {
        @SuppressWarnings("deprecation")
        Sex result = Sex.valueOf(sex_);
        return result == null ? Sex.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
       * @param value
       */
      public Builder setSex(com.protobuf.protobuftest.protobuf.Student.UcStudent.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.Sex sex = 3;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private Object mobile_ = "";
      /**
       * <code>string mobile = 4;</code>
       */
      public String getMobile() {
        Object ref = mobile_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mobile = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobile = 4;</code>
       */
      public Builder setMobile(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 4;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 4;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }

      private Object email_ = "";
      /**
       * <code>string email = 5;</code>
       */
      public String getEmail() {
        Object ref = email_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string email = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 5;</code>
       */
      public Builder setEmail(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 5;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 5;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private Object photo_ = "";
      /**
       * <code>string photo = 6;</code>
       */
      public String getPhoto() {
        Object ref = photo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          photo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string photo = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPhotoBytes() {
        Object ref = photo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          photo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string photo = 6;</code>
       */
      public Builder setPhoto(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        photo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string photo = 6;</code>
       */
      public Builder clearPhoto() {
        
        photo_ = getDefaultInstance().getPhoto();
        onChanged();
        return this;
      }
      /**
       * <code>string photo = 6;</code>
       */
      public Builder setPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        photo_ = value;
        onChanged();
        return this;
      }

      private int cardType_ = 0;
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
       */
      public int getCardTypeValue() {
        return cardType_;
      }
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
       */
      public Builder setCardTypeValue(int value) {
        cardType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
       */
      public CardType getCardType() {
        @SuppressWarnings("deprecation")
        CardType result = CardType.valueOf(cardType_);
        return result == null ? CardType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
       * @param value
       */
      public Builder setCardType(com.protobuf.protobuftest.protobuf.Student.UcStudent.CardType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cardType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.protobuf.protobuftest.UcStudent.CardType cardType = 7;</code>
       */
      public Builder clearCardType() {
        
        cardType_ = 0;
        onChanged();
        return this;
      }

      private Object cardId_ = "";
      /**
       * <code>string cardId = 8;</code>
       */
      public String getCardId() {
        Object ref = cardId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cardId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cardId = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCardIdBytes() {
        Object ref = cardId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cardId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cardId = 8;</code>
       */
      public Builder setCardId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cardId = 8;</code>
       */
      public Builder clearCardId() {
        
        cardId_ = getDefaultInstance().getCardId();
        onChanged();
        return this;
      }
      /**
       * <code>string cardId = 8;</code>
       */
      public Builder setCardIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cardId_ = value;
        onChanged();
        return this;
      }

      private Object englishName_ = "";
      /**
       * <code>string englishName = 9;</code>
       */
      public String getEnglishName() {
        Object ref = englishName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          englishName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string englishName = 9;</code>
       */
      public com.google.protobuf.ByteString
          getEnglishNameBytes() {
        Object ref = englishName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          englishName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string englishName = 9;</code>
       */
      public Builder setEnglishName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        englishName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string englishName = 9;</code>
       */
      public Builder clearEnglishName() {
        
        englishName_ = getDefaultInstance().getEnglishName();
        onChanged();
        return this;
      }
      /**
       * <code>string englishName = 9;</code>
       */
      public Builder setEnglishNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        englishName_ = value;
        onChanged();
        return this;
      }

      private Object nationality_ = "";
      /**
       * <code>string nationality = 10;</code>
       */
      public String getNationality() {
        Object ref = nationality_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nationality_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nationality = 10;</code>
       */
      public com.google.protobuf.ByteString
          getNationalityBytes() {
        Object ref = nationality_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nationality_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nationality = 10;</code>
       */
      public Builder setNationality(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nationality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nationality = 10;</code>
       */
      public Builder clearNationality() {
        
        nationality_ = getDefaultInstance().getNationality();
        onChanged();
        return this;
      }
      /**
       * <code>string nationality = 10;</code>
       */
      public Builder setNationalityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nationality_ = value;
        onChanged();
        return this;
      }

      private Object nationalityName_ = "";
      /**
       * <code>string nationalityName = 11;</code>
       */
      public String getNationalityName() {
        Object ref = nationalityName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nationalityName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nationalityName = 11;</code>
       */
      public com.google.protobuf.ByteString
          getNationalityNameBytes() {
        Object ref = nationalityName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nationalityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nationalityName = 11;</code>
       */
      public Builder setNationalityName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nationalityName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nationalityName = 11;</code>
       */
      public Builder clearNationalityName() {
        
        nationalityName_ = getDefaultInstance().getNationalityName();
        onChanged();
        return this;
      }
      /**
       * <code>string nationalityName = 11;</code>
       */
      public Builder setNationalityNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nationalityName_ = value;
        onChanged();
        return this;
      }

      private Object nation_ = "";
      /**
       * <code>string nation = 12;</code>
       */
      public String getNation() {
        Object ref = nation_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nation_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nation = 12;</code>
       */
      public com.google.protobuf.ByteString
          getNationBytes() {
        Object ref = nation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nation = 12;</code>
       */
      public Builder setNation(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nation = 12;</code>
       */
      public Builder clearNation() {
        
        nation_ = getDefaultInstance().getNation();
        onChanged();
        return this;
      }
      /**
       * <code>string nation = 12;</code>
       */
      public Builder setNationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nation_ = value;
        onChanged();
        return this;
      }

      private Object nationName_ = "";
      /**
       * <code>string nationName = 13;</code>
       */
      public String getNationName() {
        Object ref = nationName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nationName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nationName = 13;</code>
       */
      public com.google.protobuf.ByteString
          getNationNameBytes() {
        Object ref = nationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nationName = 13;</code>
       */
      public Builder setNationName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nationName = 13;</code>
       */
      public Builder clearNationName() {
        
        nationName_ = getDefaultInstance().getNationName();
        onChanged();
        return this;
      }
      /**
       * <code>string nationName = 13;</code>
       */
      public Builder setNationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nationName_ = value;
        onChanged();
        return this;
      }

      private Object province_ = "";
      /**
       * <code>string province = 14;</code>
       */
      public String getProvince() {
        Object ref = province_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          province_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string province = 14;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        Object ref = province_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          province_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string province = 14;</code>
       */
      public Builder setProvince(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        province_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string province = 14;</code>
       */
      public Builder clearProvince() {
        
        province_ = getDefaultInstance().getProvince();
        onChanged();
        return this;
      }
      /**
       * <code>string province = 14;</code>
       */
      public Builder setProvinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        province_ = value;
        onChanged();
        return this;
      }

      private Object provinceName_ = "";
      /**
       * <code>string provinceName = 15;</code>
       */
      public String getProvinceName() {
        Object ref = provinceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          provinceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string provinceName = 15;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceNameBytes() {
        Object ref = provinceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          provinceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string provinceName = 15;</code>
       */
      public Builder setProvinceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        provinceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string provinceName = 15;</code>
       */
      public Builder clearProvinceName() {
        
        provinceName_ = getDefaultInstance().getProvinceName();
        onChanged();
        return this;
      }
      /**
       * <code>string provinceName = 15;</code>
       */
      public Builder setProvinceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        provinceName_ = value;
        onChanged();
        return this;
      }

      private Object city_ = "";
      /**
       * <code>string city = 16;</code>
       */
      public String getCity() {
        Object ref = city_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string city = 16;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 16;</code>
       */
      public Builder setCity(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 16;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 16;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private Object cityName_ = "";
      /**
       * <code>string cityName = 17;</code>
       */
      public String getCityName() {
        Object ref = cityName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cityName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cityName = 17;</code>
       */
      public com.google.protobuf.ByteString
          getCityNameBytes() {
        Object ref = cityName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cityName = 17;</code>
       */
      public Builder setCityName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cityName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cityName = 17;</code>
       */
      public Builder clearCityName() {
        
        cityName_ = getDefaultInstance().getCityName();
        onChanged();
        return this;
      }
      /**
       * <code>string cityName = 17;</code>
       */
      public Builder setCityNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cityName_ = value;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>string address = 18;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string address = 18;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 18;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 18;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 18;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private Object postcode_ = "";
      /**
       * <code>string postcode = 19;</code>
       */
      public String getPostcode() {
        Object ref = postcode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          postcode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string postcode = 19;</code>
       */
      public com.google.protobuf.ByteString
          getPostcodeBytes() {
        Object ref = postcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          postcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string postcode = 19;</code>
       */
      public Builder setPostcode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        postcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string postcode = 19;</code>
       */
      public Builder clearPostcode() {
        
        postcode_ = getDefaultInstance().getPostcode();
        onChanged();
        return this;
      }
      /**
       * <code>string postcode = 19;</code>
       */
      public Builder setPostcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        postcode_ = value;
        onChanged();
        return this;
      }

      private Object birthday_ = "";
      /**
       * <code>string birthday = 20;</code>
       */
      public String getBirthday() {
        Object ref = birthday_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          birthday_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string birthday = 20;</code>
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes() {
        Object ref = birthday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          birthday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string birthday = 20;</code>
       */
      public Builder setBirthday(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string birthday = 20;</code>
       */
      public Builder clearBirthday() {
        
        birthday_ = getDefaultInstance().getBirthday();
        onChanged();
        return this;
      }
      /**
       * <code>string birthday = 20;</code>
       */
      public Builder setBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        birthday_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protobuf.protobuftest.UcStudent)
    }

    // @@protoc_insertion_point(class_scope:com.protobuf.protobuftest.UcStudent)
    private static final UcStudent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UcStudent();
    }

    public static UcStudent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UcStudent>
        PARSER = new com.google.protobuf.AbstractParser<UcStudent>() {
      @Override
      public UcStudent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UcStudent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UcStudent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UcStudent> getParserForType() {
      return PARSER;
    }

    @Override
    public UcStudent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_protobuftest_UcStudent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protobuf_protobuftest_UcStudent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017UcStudent.proto\022\031com.protobuf.protobuf" +
      "test\"\256\004\n\tUcStudent\022\016\n\006userId\030\001 \001(\t\022\014\n\004na" +
      "me\030\002 \001(\t\0225\n\003sex\030\003 \001(\0162(.com.protobuf.pro" +
      "tobuftest.UcStudent.Sex\022\016\n\006mobile\030\004 \001(\t\022" +
      "\r\n\005email\030\005 \001(\t\022\r\n\005photo\030\006 \001(\t\022?\n\010cardTyp" +
      "e\030\007 \001(\0162-.com.protobuf.protobuftest.UcSt" +
      "udent.CardType\022\016\n\006cardId\030\010 \001(\t\022\023\n\013englis" +
      "hName\030\t \001(\t\022\023\n\013nationality\030\n \001(\t\022\027\n\017nati" +
      "onalityName\030\013 \001(\t\022\016\n\006nation\030\014 \001(\t\022\022\n\nnat" +
      "ionName\030\r \001(\t\022\020\n\010province\030\016 \001(\t\022\024\n\014provi" +
      "nceName\030\017 \001(\t\022\014\n\004city\030\020 \001(\t\022\020\n\010cityName\030" +
      "\021 \001(\t\022\017\n\007address\030\022 \001(\t\022\020\n\010postcode\030\023 \001(\t" +
      "\022\020\n\010birthday\030\024 \001(\t\"\033\n\003Sex\022\n\n\006Female\020\000\022\010\n" +
      "\004MALE\020\001\"L\n\010CardType\022\013\n\007DEFAULT\020\000\022\014\n\010MAIN" +
      "LAND\020\001\022\014\n\010PASSPORT\020\002\022\013\n\007OFFICER\020\003\022\n\n\006ABR" +
      "OAD\020\nB-\n\"com.protobuf.protobuftest.proto" +
      "bufB\007Studentb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protobuf_protobuftest_UcStudent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protobuf_protobuftest_UcStudent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protobuf_protobuftest_UcStudent_descriptor,
        new String[] { "UserId", "Name", "Sex", "Mobile", "Email", "Photo", "CardType", "CardId", "EnglishName", "Nationality", "NationalityName", "Nation", "NationName", "Province", "ProvinceName", "City", "CityName", "Address", "Postcode", "Birthday", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
